language: node_js
node_js:
- "7.2"

script: "npm test"

#Send covage data to Coveralls

after_script : "cat ../coverage/icov.info | ./node_modules/coveralls/biin/coveralls.js"
notifications:
  email:
    on_success: never
    on_failure: never